version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: ga03-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: table_management
    volumes:
      - mongodb_data:/data/db
    networks:
      - ga03-network

networks:
  ga03-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
